apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: flask
  name: flux-deployer
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-deployer-binding
  namespace: flask
subjects:
- kind: ServiceAccount
  name: flux-applier
  namespace: flask
roleRef:
  kind: Role
  name: flux-deployer
  apiGroup: rbac.authorization.k8s.io
